services:
  db:
    image: postgis/postgis:15-3.4
    container_name: transit-db
    restart: always
    environment:
      - POSTGRES_USER=transitsym
      - POSTGRES_PASSWORD=metro
      - POSTGRES_DB=transit
    ports:
      - "6000:5432"
    volumes:
      - transit_system:/var/lib/postgresql/data

volumes:
  transit_system: